# Generated by Django 4.2.7 on 2025-09-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, verbose_name='Nom de famille')),
                ('prenom', models.CharField(max_length=30, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('phone', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('adresse_depart', models.TextField(verbose_name='Adresse de départ')),
                ('date_demenagement', models.DateField(verbose_name='Date de déménagement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Information Client',
                'verbose_name_plural': 'Informations Clients',
                'ordering': ['-created_at'],
            },
        ),
    ]
