# Generated by Django 4.2.7 on 2025-09-29 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demenagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_selections', models.JSONField(default=dict, help_text='Objets sélectionnés organisés par pièce', verbose_name='Sélections par pièce')),
                ('heavy_objects', models.JSONField(default=dict, help_text='Objets particuliers ou de plus de 80kg', verbose_name='Objets lourds (+80kg)')),
                ('total_volume', models.FloatField(default=0.0, help_text='Volume total calculé en mètres cubes', verbose_name='Volume total (m³)')),
                ('total_objects_count', models.IntegerField(default=0, help_text="Nombre total d'objets sélectionnés", verbose_name="Nombre total d'objets")),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('completed', 'Terminé'), ('validated', 'Validé')], default='draft', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('client_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_selections', to='demenagement.clientinformation', verbose_name='Information Client')),
            ],
            options={
                'verbose_name': 'Sélection Manuelle',
                'verbose_name_plural': 'Sélections Manuelles',
                'ordering': ['-created_at'],
            },
        ),
    ]
