# Generated by Django 4.2.7 on 2025-10-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demenagement', '0002_manualselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualselection',
            name='custom_objects',
            field=models.JSONField(default=dict, help_text="Objets ajoutés manuellement par l'utilisateur avec dimensions", verbose_name='Objets personnalisés'),
        ),
    ]
