# Generated by Django 4.2.7 on 2025-10-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demenagement', '0003_manualselection_custom_objects'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualselection',
            name='custom_heavy_objects',
            field=models.JSONField(default=dict, help_text="Objets lourds ajoutés manuellement par l'utilisateur avec dimensions", verbose_name='Objets lourds personnalisés'),
        ),
    ]
