# Generated by Django 4.2.7 on 2025-10-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demenagement', '0004_manualselection_custom_heavy_objects'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualselection',
            name='calculated_volumes',
            field=models.JSONField(default=dict, help_text='Volumes calculés selon les formules (vhouse, vfurniture, total_volume)', verbose_name='Volumes calculés'),
        ),
        migrations.AddField(
            model_name='manualselection',
            name='method',
            field=models.CharField(choices=[('manual', 'Sélection manuelle'), ('ai', 'Analyse IA'), ('superficie', 'Calcul superficie')], default='manual', max_length=20, verbose_name='Méthode de calcul'),
        ),
        migrations.AddField(
            model_name='manualselection',
            name='surface_area',
            field=models.FloatField(blank=True, help_text='Surface du logement en mètres carrés', null=True, verbose_name='Surface (m²)'),
        ),
    ]
