# Generated by Django 4.2.7 on 2025-10-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demenagement', '0005_manualselection_calculated_volumes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualselection',
            name='base_price',
            field=models.FloatField(default=0.0, help_text='Prix calculé avant ajustements', verbose_name='Prix de base (€)'),
        ),
        migrations.AddField(
            model_name='manualselection',
            name='final_price',
            field=models.FloatField(default=0.0, help_text='Prix final après tous les ajustements', verbose_name='Prix final (€)'),
        ),
    ]
