# Generated by Django 4.2.7 on 2025-10-08 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demenagement', '0006_manualselection_base_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_depart', models.TextField(verbose_name='Adresse de départ')),
                ('etage_depart', models.CharField(choices=[('RDC', 'RDC'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], default='RDC', help_text='RDC ou nombre entre 1 et 20', max_length=10, verbose_name='Étage de départ')),
                ('ascenseur_depart', models.CharField(choices=[('Non', 'Non'), ('1 personne', '1 personne'), ('2 personnes', '2 personnes'), ('3 personnes', '3 personnes'), ('4 personnes ou plus', '4 personnes ou plus')], default='Non', max_length=20, verbose_name='Ascenseur au départ')),
                ('options_depart', models.JSONField(blank=True, default=dict, help_text='Options: monte_meuble, cave_ou_garage, cours_a_traverser', verbose_name='Options départ')),
                ('has_stopover', models.BooleanField(default=False, verbose_name='Escale intermédiaire')),
                ('escale_adresse', models.TextField(blank=True, null=True, verbose_name='Adresse escale')),
                ('escale_etage', models.CharField(blank=True, choices=[('RDC', 'RDC'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], default='RDC', help_text='RDC ou nombre entre 1 et 20', max_length=10, null=True, verbose_name='Étage escale')),
                ('escale_ascenseur', models.CharField(blank=True, choices=[('Non', 'Non'), ('1 personne', '1 personne'), ('2 personnes', '2 personnes'), ('3 personnes', '3 personnes'), ('4 personnes ou plus', '4 personnes ou plus')], default='Non', max_length=20, null=True, verbose_name="Ascenseur à l'escale")),
                ('escale_options', models.JSONField(blank=True, default=dict, help_text='Options: monte_meuble, cave_ou_garage, cours_a_traverser', verbose_name='Options escale')),
                ('adresse_arrivee', models.TextField(verbose_name="Adresse d'arrivée")),
                ('etage_arrivee', models.CharField(choices=[('RDC', 'RDC'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], default='RDC', help_text='RDC ou nombre entre 1 et 20', max_length=10, verbose_name="Étage d'arrivée")),
                ('ascenseur_arrivee', models.CharField(choices=[('Non', 'Non'), ('1 personne', '1 personne'), ('2 personnes', '2 personnes'), ('3 personnes', '3 personnes'), ('4 personnes ou plus', '4 personnes ou plus')], default='Non', max_length=20, verbose_name="Ascenseur à l'arrivée")),
                ('options_arrivee', models.JSONField(blank=True, default=dict, help_text='Options: monte_meuble, cave_ou_garage, cours_a_traverser', verbose_name='Options arrivée')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('client_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='demenagement.clientinformation', verbose_name='Information Client')),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
                'ordering': ['-created_at'],
            },
        ),
    ]
