# Generated by Django 4.2.7 on 2025-10-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demenagement', '0007_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinformation',
            name='adresse_arrivee',
            field=models.TextField(default='', verbose_name="Adresse d'arrivée"),
        ),
        migrations.AddField(
            model_name='clientinformation',
            name='ascenseur_arrivee',
            field=models.CharField(choices=[('Non', 'Non'), ('1 personne', '1 personne'), ('2 personnes', '2 personnes'), ('3 personnes', '3 personnes'), ('4 personnes ou plus', '4 personnes ou plus')], default='Non', max_length=20, verbose_name="Ascenseur à l'arrivée"),
        ),
        migrations.AddField(
            model_name='clientinformation',
            name='ascenseur_depart',
            field=models.CharField(choices=[('Non', 'Non'), ('1 personne', '1 personne'), ('2 personnes', '2 personnes'), ('3 personnes', '3 personnes'), ('4 personnes ou plus', '4 personnes ou plus')], default='Non', max_length=20, verbose_name='Ascenseur au départ'),
        ),
        migrations.AddField(
            model_name='clientinformation',
            name='escale_adresse',
            field=models.TextField(blank=True, default='', verbose_name='Adresse escale'),
        ),
        migrations.AddField(
            model_name='clientinformation',
            name='escale_ascenseur',
            field=models.CharField(blank=True, choices=[('Non', 'Non'), ('1 personne', '1 personne'), ('2 personnes', '2 personnes'), ('3 personnes', '3 personnes'), ('4 personnes ou plus', '4 personnes ou plus')], default='Non', max_length=20, verbose_name="Ascenseur à l'escale"),
        ),
        migrations.AddField(
            model_name='clientinformation',
            name='escale_etage',
            field=models.CharField(blank=True, choices=[('RDC', 'RDC'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], default='RDC', max_length=10, verbose_name='Étage escale'),
        ),
        migrations.AddField(
            model_name='clientinformation',
            name='escale_options',
            field=models.JSONField(blank=True, default=dict, verbose_name='Options escale'),
        ),
        migrations.AddField(
            model_name='clientinformation',
            name='etage_arrivee',
            field=models.CharField(choices=[('RDC', 'RDC'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], default='RDC', max_length=10, verbose_name="Étage d'arrivée"),
        ),
        migrations.AddField(
            model_name='clientinformation',
            name='etage_depart',
            field=models.CharField(choices=[('RDC', 'RDC'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], default='RDC', max_length=10, verbose_name='Étage de départ'),
        ),
        migrations.AddField(
            model_name='clientinformation',
            name='has_stopover',
            field=models.BooleanField(default=False, verbose_name='Escale intermédiaire'),
        ),
        migrations.AddField(
            model_name='clientinformation',
            name='options_arrivee',
            field=models.JSONField(blank=True, default=dict, verbose_name='Options arrivée'),
        ),
        migrations.AddField(
            model_name='clientinformation',
            name='options_depart',
            field=models.JSONField(blank=True, default=dict, help_text='Options: monte_meuble, cave_ou_garage, cours_a_traverser', verbose_name='Options départ'),
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='adresse_depart',
            field=models.TextField(default='', verbose_name='Adresse de départ'),
        ),
    ]
