# Generated by Django 4.2.28 on 2026-02-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demenagement', '0008_clientinformation_adresse_arrivee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='ascenseur_arrivee',
            field=models.CharField(choices=[('Non', 'Non'), ('2-3 personnes', '2-3 personnes'), ('3-4 personnes', '3-4 personnes'), ('4-6 personnes', '4-6 personnes'), ('6-8 personnes ou plus', '6-8 personnes ou plus')], default='Non', max_length=25, verbose_name="Ascenseur à l'arrivée"),
        ),
        migrations.AlterField(
            model_name='address',
            name='ascenseur_depart',
            field=models.CharField(choices=[('Non', 'Non'), ('2-3 personnes', '2-3 personnes'), ('3-4 personnes', '3-4 personnes'), ('4-6 personnes', '4-6 personnes'), ('6-8 personnes ou plus', '6-8 personnes ou plus')], default='Non', max_length=25, verbose_name='Ascenseur au départ'),
        ),
        migrations.AlterField(
            model_name='address',
            name='escale_ascenseur',
            field=models.CharField(blank=True, choices=[('Non', 'Non'), ('2-3 personnes', '2-3 personnes'), ('3-4 personnes', '3-4 personnes'), ('4-6 personnes', '4-6 personnes'), ('6-8 personnes ou plus', '6-8 personnes ou plus')], default='Non', max_length=25, null=True, verbose_name="Ascenseur à l'escale"),
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='ascenseur_arrivee',
            field=models.CharField(choices=[('Non', 'Non'), ('2-3 personnes', '2-3 personnes'), ('3-4 personnes', '3-4 personnes'), ('4-6 personnes', '4-6 personnes'), ('6-8 personnes ou plus', '6-8 personnes ou plus')], default='Non', max_length=25, verbose_name="Ascenseur à l'arrivée"),
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='ascenseur_depart',
            field=models.CharField(choices=[('Non', 'Non'), ('2-3 personnes', '2-3 personnes'), ('3-4 personnes', '3-4 personnes'), ('4-6 personnes', '4-6 personnes'), ('6-8 personnes ou plus', '6-8 personnes ou plus')], default='Non', max_length=25, verbose_name='Ascenseur au départ'),
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='escale_ascenseur',
            field=models.CharField(blank=True, choices=[('Non', 'Non'), ('2-3 personnes', '2-3 personnes'), ('3-4 personnes', '3-4 personnes'), ('4-6 personnes', '4-6 personnes'), ('6-8 personnes ou plus', '6-8 personnes ou plus')], default='Non', max_length=25, verbose_name="Ascenseur à l'escale"),
        ),
        migrations.AlterField(
            model_name='manualselection',
            name='method',
            field=models.CharField(choices=[('manual', 'Sélection manuelle'), ('ai', 'Analyse IA'), ('superficie', 'Calcul superficie')], default='manual', max_length=25, verbose_name='Méthode de calcul'),
        ),
        migrations.AlterField(
            model_name='manualselection',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('completed', 'Terminé'), ('validated', 'Validé')], default='draft', max_length=25, verbose_name='Statut'),
        ),
    ]
