# Generated by Django 4.2.28 on 2026-02-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demenagement', '0009_alter_address_ascenseur_arrivee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='escale_options',
            field=models.JSONField(blank=True, default=dict, help_text='Options: monte_meuble, cave_ou_garage, cours_a_traverser, distance_portage', verbose_name='Options escale'),
        ),
        migrations.AlterField(
            model_name='address',
            name='options_arrivee',
            field=models.JSONField(blank=True, default=dict, help_text='Options: monte_meuble, cave_ou_garage, cours_a_traverser, distance_portage', verbose_name='Options arrivée'),
        ),
        migrations.AlterField(
            model_name='address',
            name='options_depart',
            field=models.JSONField(blank=True, default=dict, help_text='Options: monte_meuble, cave_ou_garage, cours_a_traverser, distance_portage', verbose_name='Options départ'),
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='options_depart',
            field=models.JSONField(blank=True, default=dict, help_text='Options: monte_meuble, cave_ou_garage, cours_a_traverser, distance_portage', verbose_name='Options départ'),
        ),
    ]
