# Generated by Django 4.2.28 on 2026-02-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demenagement', '0010_alter_address_escale_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='demi_etage_depart',
            field=models.BooleanField(default=False, verbose_name='Ascenseur desservant uniquement un demi-étage (départ)'),
        ),
        migrations.AddField(
            model_name='address',
            name='demi_etage_escale',
            field=models.BooleanField(default=False, verbose_name='Ascenseur desservant uniquement un demi-étage (escale)'),
        ),
        migrations.AddField(
            model_name='clientinformation',
            name='demi_etage_arrivee',
            field=models.BooleanField(default=False, verbose_name='Ascenseur desservant uniquement un demi-étage (arrivée)'),
        ),
    ]
