# Generated by Django 4.2.28 on 2026-02-16 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demenagement', '0012_add_demi_etage_to_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientinformation',
            name='demi_etage_arrivee',
        ),
        migrations.RemoveField(
            model_name='clientinformation',
            name='demi_etage_depart',
        ),
    ]
