# Generated by Django 4.2.28 on 2026-03-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demenagement', '0013_remove_clientinformation_demi_etage_arrivee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualselection',
            name='anciennete_logement',
            field=models.CharField(blank=True, choices=[('0_2', '0–2 ans'), ('2_5', '2–5 ans'), ('5_plus', 'Plus de 5 ans')], help_text='Depuis quand vous êtes dans ce logement', max_length=20, null=True, verbose_name='Ancienneté dans le logement'),
        ),
        migrations.AddField(
            model_name='manualselection',
            name='logement_type',
            field=models.CharField(blank=True, choices=[('aerien', 'Aérien'), ('normal', 'Normal'), ('charge', 'Chargé')], help_text='Aérien, normal ou chargé', max_length=20, null=True, verbose_name='Votre logement'),
        ),
    ]
