# Generated by Django 4.2.28 on 2026-04-02 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demenagement', '0014_manualselection_anciennete_logement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevisQuoteNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(blank=True, db_index=True, help_text='Ex. gv2604021430157 — gv + date + heure + id ligne', max_length=64, null=True, unique=True, verbose_name='Référence devis')),
                ('final_price', models.FloatField(default=0.0, verbose_name='Prix final (€)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis_quote_notifications', to='demenagement.clientinformation', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Devis envoyé par email',
                'verbose_name_plural': 'Devis envoyés par email',
                'ordering': ['-created_at'],
            },
        ),
    ]
