# Generated by Django 4.2.28 on 2026-04-02 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demenagement', '0015_devis_quote_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='devisquotenotification',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Dossier trajet : même id que dans Adresses', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devis_quote_notifications', to='demenagement.address', verbose_name='Adresse (réservation)'),
        ),
        migrations.AlterField(
            model_name='devisquotenotification',
            name='reference_code',
            field=models.CharField(blank=True, db_index=True, help_text='Ex. gv0204261430132 — suffixe = id Adresse (réservation)', max_length=64, null=True, unique=True, verbose_name='Référence devis'),
        ),
    ]
