# Generated by Django 4.2.28 on 2026-05-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demenagement', '0016_devis_quote_notification_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinformation',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Adresse email'),
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='nom',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Nom de famille'),
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='prenom',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Prénom'),
        ),
    ]
