# Generated by Django 4.2.7 on 2025-09-26 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_detector', '0002_clientinformation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientInformation',
        ),
    ]
