# Generated by Django 4.2.7 on 2025-10-02 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_detector', '0003_delete_clientinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('total_objects', models.IntegerField(default=0)),
                ('total_volume', models.FloatField(default=0.0)),
                ('is_finalized', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='ai_detector.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('volume_per_unit', models.FloatField(default=0.0)),
                ('total_volume', models.FloatField(default=0.0)),
                ('is_ai_detected', models.BooleanField(default=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='ai_detector.roomanalysis')),
            ],
        ),
    ]
