# Generated by Django 4.2.7 on 2025-10-07 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_detector', '0004_roomanalysis_roomobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomobject',
            name='room_analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_objects', to='ai_detector.roomanalysis'),
        ),
    ]
