# Generated by Django 4.2.7 on 2025-10-07 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_detector', '0006_alter_quote_user_alter_room_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeavyObjectSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('volume_per_unit', models.FloatField(default=0.0)),
                ('length', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heavy_objects', to='ai_detector.room')),
            ],
        ),
    ]
